[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "v0.110.0+extended"
  GO_VERSION = "1.16"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = ["feed.xml"] # Can't handle xml:base and relative paths

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.8

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
