name: Deploy to Netlify

on:
  push:
    branches: [v4]

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git-based last modification date

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2

      - name: Enable PNPM
        run: corepack enable && asdf reshim nodejs

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm exec ./quartz/bootstrap-cli.mjs build

      - name: Netlify deploy
        uses: netlify/actions/cli@master
        id: netlify-deploy
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Link checker
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: ${{steps.netlify-deploy.outputs.NETLIFY_URL}}
          recurse: true
          verbosity: "INFO"

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: ${{steps.netlify-deploy.outputs.NETLIFY_URL}}
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

